frame_id: "world_origin"

leader_msg: "mpc"
frame_publish: "utm_navsat"

timer_main:
  rate: 1.0 # [Hz]

timer_pose:
  rate: 1.0 # [Hz]

timer_comm:
  rate: 1.0 # [Hz]
  timeout: 5.0 # [s]

center:
  x: 0.0 # [m]
  y: 0.0 # [m]
  z: 5.0 # [m]

dimensions:
  x: 150.0 # [m]
  y: 150.0 # [m]

angle: 0.0
lateral_scale: 1.0
side: 6.0

octomap_planner_set: true